#! /bin/sh

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

#if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
#	xrandr --output "$mainmonitor" --auto --output LVDS-1 --off
#fi

# Start workspaces on the main monitor.
bspc monitor $mainmonitor -d 1 2 3 4 5 6 7 8 9 10

bspc desktop -f 1

bspc config border_width         3
bspc config window_gap          15
bspc config top_padding 24

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a matplotlib state=floating

bspc config focused_border_color "#73a6e4"

#bspc config focus_follows_pointer true

bspc config click_to_focus button1

killall sxhkd
killall compton
sxhkd &
bash ~/.scripts/launch_polybar.sh &
bash ~/.scripts/launch_nitrogen.sh &
compton -c -b &
nm-applet &
